In [ ]:
# перед началом работы не забудьте скачать файл train.json.zip с Kaggle и разархивировать его
import json
import pandas as pd

# сразу загрузим датасет от Renthop
with open('drive/MyDrive/ML/mlcourse.ai/Lecture6/train.json', 'r') as raw_data:
    data = json.load(raw_data)
    df = pd.DataFrame(data)
df

bathrooms  bedrooms  ...           street_address interest_level
4             1.0         1  ...      145 Borinquen Place         medium
6             1.0         2  ...            230 East 44th            low
9             1.0         2  ...     405 East 56th Street         medium
10            1.5         3  ...  792 Metropolitan Avenue         medium
15            1.0         0  ...     340 East 34th Street            low
...           ...       ...  ...                      ...            ...
124000        1.0         3  ...         620 W 171 Street            low
124002        1.0         2  ...            3333 Broadway         medium
124004        1.0         1  ...     210 Brighton 15th St         medium
124008        1.0         2  ...     350 West 21st Street         medium
124009        1.0         3  ...            123 E 54th St           high

[49352 rows x 15 columns]

In [ ]:
from functools import reduce
import numpy as np

texts = [['i', 'have', 'a', 'cat'],
         ['he', 'have', 'a', 'dog'],
         ['he', 'and', 'i', 'have', 'a', 'cat', 'and', 'a', 'dog']]

dictionary = list(enumerate(set(reduce(lambda x, y: x + y, texts))))
dictionary

[(0, 'cat'),
 (1, 'i'),
 (2, 'he'),
 (3, 'and'),
 (4, 'dog'),
 (5, 'a'),
 (6, 'have')]

In [ ]:
def vectorize(text):
    vector = np.zeros(len(dictionary))
    for i, word in dictionary:
        num = 0
        for w in text:
            if w == word:
                num += 1
        if num:
            vector[i] = num
    return vector

for t in texts:
    print(vectorize(t))

[1. 1. 0. 0. 0. 1. 1.]
[0. 0. 1. 0. 1. 1. 1.]
[1. 1. 1. 2. 1. 2. 1.]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(ngram_range=(1,1)) 
vect.fit_transform(['no i have cows', 'i have no cows']).toarray()

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
vect.vocabulary_

{'cows': 0, 'have': 1, 'no': 2}

In [ ]:
vect = CountVectorizer(ngram_range=(1,2)) 
vect.fit_transform(['no i have cows', 'i have no cows']).toarray()

array([[1, 1, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 0]])

In [ ]:
vect.vocabulary_

{'cows': 0,
 'have': 1,
 'have cows': 2,
 'have no': 3,
 'no': 4,
 'no cows': 5,
 'no have': 6}

In [ ]:
from scipy.spatial.distance import euclidean
vect = CountVectorizer(ngram_range=(3,3), analyzer='char_wb')
n1, n2, n3, n4 = vect.fit_transform(['иванов', 'петров', 'петренко', 'смит']).toarray()
euclidean(n1, n2)

3.1622776601683795

In [ ]:
n1,n2,n3,n4

(array([1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]))

In [ ]:
vect.vocabulary_

{' ив': 0,
 ' пе': 1,
 ' см': 2,
 'ано': 3,
 'ван': 4,
 'енк': 5,
 'етр': 6,
 'ива': 7,
 'ит ': 8,
 'ко ': 9,
 'мит': 10,
 'нко': 11,
 'нов': 12,
 'ов ': 13,
 'пет': 14,
 'рен': 15,
 'ров': 16,
 'сми': 17,
 'тре': 18,
 'тро': 19}

In [ ]:
euclidean(n2, n3)

2.8284271247461903

In [ ]:
euclidean(n3, n4)

3.4641016151377544

In [ ]:
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from scipy.misc import face
import numpy as np

resnet_settings = {'include_top': False, 'weights': 'imagenet'}
resnet = ResNet50(**resnet_settings)

img = image.array_to_img(face())
# какой милый енот! 
img = img.resize((224, 224))
# в реальной жизни может понадобиться внимательнее относиться к ресайзу
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
# нужно дополнительное измерение, т.к. модель рассчитана на работу с массивом изображений

features = resnet.predict(x)
features

94773248/94765736 [==============================] - 1s 0us/step


array([[[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.36833775, 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.64314723, 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.54946536, 0. 

In [ ]:
pip install pytesseract

  Created wheel for pytesseract: filename=pytesseract-0.3.8-py2.py3-none-any.whl size=14071 sha256=42518bb46039a9f2a5c8ecdc1eab79540eb95fce712948c8c2e1f72fc17499bb
  Stored in directory: /root/.cache/pip/wheels/a2/66/45/88bf1b2d428817a006944b9730b27d6861b776e05a9e262bd4
Successfully built pytesseract


In [ ]:
pip install tesseract

     |████████████████████████████████| 45.6MB 65kB/s 
  Created wheel for tesseract: filename=tesseract-0.1.3-cp37-none-any.whl size=45562571 sha256=200776677873321ad1d84cd265b3b297bbc66de24d9e29850681f63cd534de20
  Stored in directory: /root/.cache/pip/wheels/82/1f/d9/24797b123379e4ea9511cf660835468b62dad609634cad2aba
Successfully built tesseract


In [ ]:
pip install tesseract-ocr

  ERROR: Failed building wheel for tesseract-ocr
  Running setup.py clean for tesseract-ocr
Failed to build tesseract-ocr
    Running setup.py install for tesseract-ocr ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tq3u64g2/tesseract-ocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tq3u64g2/tesseract-ocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-y9lr6dkh/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.


In [ ]:
pytesseract.pytesseract.tesseract_cmd = r'/usr/local/bin/pytesseract'

NameError: ignored

In [ ]:
import pytesseract
from PIL import Image
import requests
from io import BytesIO
img = 'http://ohscurrent.org/wp-content/uploads/2015/09/domus-01-google.jpg'
img = requests.get(img)
img = Image.open(BytesIO(img.content))
text = pytesseract.image_to_string(img)
text

In [ ]:
pip install reverse_geocoder

In [ ]:
import reverse_geocoder as revgc
revgc.search((df.latitude, df.longitude))

In [ ]:
df['dow'] = df['created'].apply(lambda x: x.date().weekday())
df['is_weekend'] = df['created'].apply(lambda x: 1 if x.date().weekday() in (5, 6) else 0)

AttributeError: ignored